
services:
  mariadb1:
    image: mariadb:latest
    container_name: mariadb-1
    environment:
      MYSQL_ROOT_PASSWORD: shussk02
      MYSQL_DATABASE: mydatabase
    volumes:
      - ./mariadb1/50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
      - ./mariadb1/init-db:/docker-entrypoint-initdb.d
    ports:
      - "13306:3306"
    networks:
      mariadb_network:
        aliases:
          - mariadb1_host
    

  mariadb2:
    image: mariadb:latest
    container_name: mariadb-2
    environment:
      MYSQL_ROOT_PASSWORD: shussk02
    volumes:
      - ./mariadb2/50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
      - ./mariadb2/init-db:/docker-entrypoint-initdb.d
    ports:
      - "23306:3306"
    depends_on:
      - mariadb1
    networks:
      mariadb_network:
        aliases:
          - mariadb2_host

  mariadb3:
    image: mariadb:latest
    container_name: mariadb-3
    environment:
      MYSQL_ROOT_PASSWORD: shussk02
    volumes:
      - ./mariadb3/50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
      - ./mariadb3/init-db:/docker-entrypoint-initdb.d
    ports:
      - "33306:3306"
    depends_on:
      - mariadb1
    networks:
      mariadb_network:
        aliases:
          - mariadb3_host

  maxscale:
    image: mariadb/maxscale:latest
    container_name: maxscale
    volumes:
      - ./maxscale/maxscale.cnf:/etc/maxscale.cnf
    ports:
      - "4007:4007"
    depends_on:
      - mariadb1
      - mariadb2
      - mariadb3
    networks:
      mariadb_network:
        aliases:
          - max_host

  app:
    build:
      context: .
    command:
      - bash
      - -c
      - |
        python manage.py makemigrations --no-input &&
        python manage.py migrate polls 0008 --fake &&
        python manage.py migrate --no-input &&
        python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - mariadb1
      - mariadb2
      - mariadb3
      - maxscale
    networks:
      mariadb_network:
        aliases:
          - django_host

networks:
  mariadb_network:
    name: mariadb_net
    driver: bridge
    ipam: 
      driver: default
