# Generated by Django 4.2.11 on 2024-05-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Nombre', models.CharField(max_length=255)),
                ('Apellido1', models.CharField(max_length=255)),
                ('Apellido2', models.CharField(max_length=255)),
                ('Telefono', models.IntegerField()),
                ('Cumpleaños', models.DateTimeField()),
            ],
            options={
                'db_table': 'dynamicmodel',
            },
        ),
    ]
