# Generated by Django 4.2.11 on 2024-05-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Nombre', models.CharField(max_length=255)),
                ('Apellidos', models.CharField(max_length=255)),
                ('Curso', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Edad', models.IntegerField()),
            ],
            options={
                'db_table': 'newmodel',
            },
        ),
        migrations.DeleteModel(
            name='DynamicModel',
        ),
    ]
