# Generated by Django 4.2.8 on 2023-12-13 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_person_options_alter_person_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['id'], 'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
    ]
