# Generated by Django 4.2.11 on 2024-05-03 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_newmodel_delete_dynamicmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newmodel',
            name='Curso',
        ),
        migrations.RemoveField(
            model_name='newmodel',
            name='Email',
        ),
    ]
