# Generated by Django 4.2.11 on 2024-05-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_newmodel_curso_remove_newmodel_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csv_newmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'csv_newmodel',
            },
        ),
        migrations.DeleteModel(
            name='NewModel',
        ),
    ]
