# Generated by Django 4.2.8 on 2023-12-13 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_person_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='apellidos',
            new_name='Apellidos',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='correo',
            new_name='Correo',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='curso',
            new_name='Curso',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='nombre',
            new_name='Nombre',
        ),
    ]
