# Generated by Django 4.2.11 on 2024-07-15 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_newmodel_delete_newtable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewModel',
        ),
    ]
